.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. feathercoin_qt test_feathercoin_qt
clean: FORCE
	$(MAKE) -C .. feathercoin_qt_clean test_feathercoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_feathercoin_qt_check
feathercoin-qt feathercoin-qt.exe: FORCE
	 $(MAKE) -C .. feathercoin_qt
